### ISSUE TITLE
Translator crashes when supplied reader doesn't exist.

### ISSUE THREAD

**Issue by jlblcc** [adiwg/mdTranslator#10]
Is this expected behavior, or should we provide a more useful error message?

The error output is:
```
TypeError: no implicit conversion of nil into String
    .../Projects/ADIwg/adiwgTranslator/mdTranslator/lib/adiwg/mdtranslator.rb:93:in `+'
    .../Projects/ADIwg/adiwgTranslator/mdTranslator/lib/adiwg/mdtranslator.rb:93:in `reader_module'
```

**Comment by stansmith907** [comment]
Patched mdTranslator to catch missing and nil reader and writer names.
