### ISSUE TITLE
sbJson to mdJson translation fails

### ISSUE THREAD

**Issue by jlblcc** [adiwg/mdTranslator#116]
Failing with this ScienceBase item: https://www.sciencebase.gov/catalog/item/589a36bfe4b0efcedb71a61c?format=json

Looks like there's a problem with generating the associatedResources. 

Stack trace:

```
xxxxx/.rvm/gems/ruby-2.4.0/gems/adiwg-mdtranslator-2.1.0/lib/adiwg/mdtranslator/writers/mdJson/sections/mdJson_resourceType.rb:19:in `[]': no implicit conversion of Symbol into Integer (TypeError)
	from xxxxx/.rvm/gems/ruby-2.4.0/gems/adiwg-mdtranslator-2.1.0/lib/adiwg/mdtranslator/writers/mdJson/sections/mdJson_resourceType.rb:19:in `block in build'
	from xxxxx/.rvm/gems/ruby-2.4.0/gems/jbuilder-2.7.0/lib/jbuilder.rb:18:in `initialize'
	from xxxxx/.rvm/gems/ruby-2.4.0/gems/adiwg-mdtranslator-2.1.0/lib/adiwg/mdtranslator/writers/mdJson/sections/mdJson_resourceType.rb:18:in `new'
	from xxxxx/.rvm/gems/ruby-2.4.0/gems/adiwg-mdtranslator-2.1.0/lib/adiwg/mdtranslator/writers/mdJson/sections/mdJson_resourceType.rb:18:in `build'
	from xxxxx/.rvm/gems/ruby-2.4.0/gems/adiwg-mdtranslator-2.1.0/lib/adiwg/mdtranslator/writers/mdJson/mdJson_writer.rb:48:in `block in json_map'
	from xxxxx/.rvm/gems/ruby-2.4.0/gems/adiwg-mdtranslator-2.1.0/lib/adiwg/mdtranslator/writers/mdJson/mdJson_writer.rb:48:in `map'
	from xxxxx/.rvm/gems/ruby-2.4.0/gems/adiwg-mdtranslator-2.1.0/lib/adiwg/mdtranslator/writers/mdJson/mdJson_writer.rb:48:in `json_map'
	from xxxxx/.rvm/gems/ruby-2.4.0/gems/adiwg-mdtranslator-2.1.0/lib/adiwg/mdtranslator/writers/mdJson/sections/mdJson_associatedResource.rb:25:in `block in build'
	from xxxxx/.rvm/gems/ruby-2.4.0/gems/jbuilder-2.7.0/lib/jbuilder.rb:18:in `initialize'
	from xxxxx/.rvm/gems/ruby-2.4.0/gems/adiwg-mdtranslator-2.1.0/lib/adiwg/mdtranslator/writers/mdJson/sections/mdJson_associatedResource.rb:22:in `new'
	from xxxxx/.rvm/gems/ruby-2.4.0/gems/adiwg-mdtranslator-2.1.0/lib/adiwg/mdtranslator/writers/mdJson/sections/mdJson_associatedResource.rb:22:in `build'
	from xxxxx/.rvm/gems/ruby-2.4.0/gems/adiwg-mdtranslator-2.1.0/lib/adiwg/mdtranslator/writers/mdJson/mdJson_writer.rb:48:in `block in json_map'
	from xxxxx/.rvm/gems/ruby-2.4.0/gems/adiwg-mdtranslator-2.1.0/lib/adiwg/mdtranslator/writers/mdJson/mdJson_writer.rb:48:in `map'
	from xxxxx/.rvm/gems/ruby-2.4.0/gems/adiwg-mdtranslator-2.1.0/lib/adiwg/mdtranslator/writers/mdJson/mdJson_writer.rb:48:in `json_map'
	from xxxxx/.rvm/gems/ruby-2.4.0/gems/adiwg-mdtranslator-2.1.0/lib/adiwg/mdtranslator/writers/mdJson/sections/mdJson_metadata.rb:32:in `block in build'
	from xxxxx/.rvm/gems/ruby-2.4.0/gems/jbuilder-2.7.0/lib/jbuilder.rb:18:in `initialize'
	from xxxxx/.rvm/gems/ruby-2.4.0/gems/adiwg-mdtranslator-2.1.0/lib/adiwg/mdtranslator/writers/mdJson/sections/mdJson_metadata.rb:27:in `new'
	from xxxxx/.rvm/gems/ruby-2.4.0/gems/adiwg-mdtranslator-2.1.0/lib/adiwg/mdtranslator/writers/mdJson/sections/mdJson_metadata.rb:27:in `build'
	from xxxxx/.rvm/gems/ruby-2.4.0/gems/adiwg-mdtranslator-2.1.0/lib/adiwg/mdtranslator/writers/mdJson/sections/mdJson_mdJson.rb:34:in `block in build'
	from xxxxx/.rvm/gems/ruby-2.4.0/gems/jbuilder-2.7.0/lib/jbuilder.rb:18:in `initialize'
	from xxxxx/.rvm/gems/ruby-2.4.0/gems/adiwg-mdtranslator-2.1.0/lib/adiwg/mdtranslator/writers/mdJson/sections/mdJson_mdJson.rb:22:in `new'
	from xxxxx/.rvm/gems/ruby-2.4.0/gems/adiwg-mdtranslator-2.1.0/lib/adiwg/mdtranslator/writers/mdJson/sections/mdJson_mdJson.rb:22:in `build'
	from xxxxx/.rvm/gems/ruby-2.4.0/gems/adiwg-mdtranslator-2.1.0/lib/adiwg/mdtranslator/writers/mdJson/mdJson_writer.rb:28:in `startWriter'
	from xxxxx/.rvm/gems/ruby-2.4.0/gems/adiwg-mdtranslator-2.1.0/lib/adiwg/mdtranslator/writers/mdWriters.rb:41:in `handleWriter'
	from xxxxx/.rvm/gems/ruby-2.4.0/gems/adiwg-mdtranslator-2.1.0/lib/adiwg/mdtranslator.rb:173:in `translate'
	from xxxxx/.rvm/gems/ruby-2.4.0/gems/adiwg-mdtranslator-2.1.0/lib/adiwg/mdtranslator_cli.rb:66:in `translate'
	from xxxxx/.rvm/gems/ruby-2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from xxxxx/.rvm/gems/ruby-2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from xxxxx/.rvm/gems/ruby-2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from xxxxx/.rvm/gems/ruby-2.4.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from xxxxx/.rvm/gems/ruby-2.4.0/gems/adiwg-mdtranslator-2.1.0/bin/mdtranslator:9:in `<top (required)>'
	from xxxxx/.rvm/gems/ruby-2.4.0/bin/mdtranslator:22:in `load'
	from xxxxx/.rvm/gems/ruby-2.4.0/bin/mdtranslator:22:in `<main>'
```

**Comment by stansmith907** [comment]
Found problem.  sbJson reader for *relatedItems* was not placing *browseCategories* in mdTranslator *resourceType* objects.  This was only true for instances of browse categories from related items so escaped some tests.  I refactored to route these through the same code as that used by other sbJson modules.  Also patched and enhanced tests.  

On another issue.  I patched another test that was failing.  The scienceBase extent id that I was using to test 404 conditions is now mysteriously working.  I replaced that with 5551212.  It seems all the easy ones like 1111111 or 100 have valid returns as part the scienceBase test system.
